//search_by_vehicle
export const SEARCH_BY_VECHICLE = "SEARCH_BY_VECHICLE";
export const SEARCH_BY_VECHICLE_LOADING = "SEARCH_BY_VECHICLE_LOADING";
export const SEARCH_BY_VECHICLE_SUCCESS = "SEARCH_BY_VECHICLE_SUCCESS";
export const SEARCH_BY_VECHICLE_ERROR = "SEARCH_BY_VECHICLE_ERROR";

//update user profile
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_LOADING = "UPDATE_PROFILE_LOADING";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

// get friend list
export const GET_FRIEND_LIST = "GET_FRIEND_LIST";
export const GET_FRIEND_LIST_LOADING = "GET_FRIEND_LIST_LOADING";
export const GET_FRIEND_LIST_SUCCESS = "GET_FRIEND_LIST_SUCCESS";
export const GET_FRIEND_LIST_ERROR = "GET_FRIEND_LIST_ERROR";

// get friend details
export const GET_FRIEND_DETAILS = "GET_FRIEND_DETAILS";
export const GET_FRIEND_DETAILS_LOADING = "GET_FRIEND_DETAILS_LOADING";
export const GET_FRIEND_DETAILS_SUCCESS = "GET_FRIEND_DETAILS_SUCCESS";
export const GET_FRIEND_DETAILS_ERROR = "GET_FRIEND_DETAILS_ERROR";


//add friend

export const ADD_FRIEND = "ADD_FRIEND";
export const ADD_FRIEND_LOADING = "ADD_FRIEND_LOADING";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const ADD_FRIEND_ERROR = "ADD_FRIEND_ERROR";

// ADD THEME LIGHT AND DARK
export const SWITCH_THEME = "SWITCH_THEME";
