//search_by_vehicle
export const SEARCH_BY_VECHICLE = "SEARCH_BY_VECHICLE";
export const SEARCH_BY_VECHICLE_LOADING = "SEARCH_BY_VECHICLE_LOADING";
export const SEARCH_BY_VECHICLE_SUCCESS = "SEARCH_BY_VECHICLE_SUCCESS";
export const SEARCH_BY_VECHICLE_ERROR = "SEARCH_BY_VECHICLE_ERROR";


//update user profile
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_LOADING = "UPDATE_PROFILE_LOADING";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

// ADD THEME LIGHT AND DARK
export const SWITCH_THEME = "SWITCH_THEME";
