//search_by_vehicle
export const SEARCH_BY_VECHICLE = "SEARCH_BY_VECHICLE";
export const SEARCH_BY_VECHICLE_LOADING = "SEARCH_BY_VECHICLE_LOADING";
export const SEARCH_BY_VECHICLE_SUCCESS = "SEARCH_BY_VECHICLE_SUCCESS";
export const SEARCH_BY_VECHICLE_ERROR = "SEARCH_BY_VECHICLE_ERROR";



// ADD THEME LIGHT AND DARK
export const SWITCH_THEME = "SWITCH_THEME";
