export const RECEIVED_CHAT_MESSAGE = "RECEIVED_CHAT_MESSAGE";

//msg listing
export const MESSAGES_LIST = "MESSAGES_LIST";
export const MESSAGES_LIST_LOADING = "MESSAGES_LIST_LOADING";
export const MESSAGES_LIST_SUCCESS = "MESSAGES_LIST_SUCCESS";
export const MESSAGES_LIST_ERROR = "MESSAGES_LIST_ERROR";

// msg details
export const MESSAGES_DETAILS = "MESSAGES_DETAILS";
export const MESSAGES_DETAILS_LOADING = "MESSAGES_DETAILS_LOADING";
export const MESSAGES_DETAILS_SUCCESS = "MESSAGES_DETAILS_SUCCESS";
export const MESSAGES_DETAILS_ERROR = "MESSAGES_DETAILS_ERROR";

// insert message
export const INSERT_MESSAGES = "INSERT_MESSAGES";
export const INSERT_MESSAGES_LOADING = "INSERT_MESSAGES_LOADING";
export const INSERT_MESSAGES_SUCCESS = "INSERT_MESSAGES_SUCCESS";
export const INSERT_MESSAGES_ERROR = "INSERT_MESSAGES_ERROR";

// read message
export const READ_MESSAGES = "READ_MESSAGES";
export const READ_MESSAGES_LOADING = "READ_MESSAGES_LOADING";
export const READ_MESSAGES_SUCCESS = "READ_MESSAGES_SUCCESS";
export const READ_MESSAGES_ERROR = "READ_MESSAGES_ERROR";

// block user
export const BLOCK_USER = "BLOCK_USER";
export const BLOCK_USER_LOADING = "BLOCK_USER_LOADING";
export const BLOCK_USER_SUCCESS = "BLOCK_USER_SUCCESS";
export const BLOCK_USER_ERROR = "BLOCK_USER_ERROR";

// report user
export const REPORT_USER = "REPORT_USER";
export const REPORT_USER_LOADING = "REPORT_USER_LOADING";
export const REPORT_USER_SUCCESS = "REPORT_USER_SUCCESS";
export const REPORT_USER_ERROR = "REPORT_USER_ERROR";

//social share friends list
export const SOCIAL_SHARE_FRIEND = "SOCIAL_SHARE_FRIEND";
export const SOCIAL_SHARE_FRIEND_LOADING = "SOCIAL_SHARE_FRIEND_LOADING";
export const SOCIAL_SHARE_FRIEND_SUCCESS = "SOCIAL_SHARE_FRIEND_SUCCESS";
export const SOCIAL_SHARE_FRIEND_ERROR = "SOCIAL_SHARE_FRIEND_ERROR";

// share social profiles

export const SHARE_SOCIAL_PROFILES = "SHARE_SOCIAL_PROFILES";
export const SHARE_SOCIAL_PROFILES_LOADING = "SHARE_SOCIAL_PROFILES_LOADING";
export const SHARE_SOCIAL_PROFILES_SUCCESS = "SHARE_SOCIAL_PROFILES_SUCCESS";
export const SHARE_SOCIAL_PROFILES_ERROR = "SHARE_SOCIAL_PROFILES_ERROR";

// ADD THEME LIGHT AND DARK
export const SWITCH_THEME = "SWITCH_THEME";
