//msg listing
export const MESSAGES_LIST = "MESSAGES_LIST";
export const MESSAGES_LIST_LOADING = "MESSAGES_LIST_LOADING";
export const MESSAGES_LIST_SUCCESS = "MESSAGES_LIST_SUCCESS";
export const MESSAGES_LIST_ERROR = "MESSAGES_LIST_ERROR";

// msg details
export const MESSAGES_DETAILS = "MESSAGES_DETAILS";
export const MESSAGES_DETAILS_LOADING = "MESSAGES_DETAILS_LOADING";
export const MESSAGES_DETAILS_SUCCESS = "MESSAGES_DETAILS_SUCCESS";
export const MESSAGES_DETAILS_ERROR = "MESSAGES_DETAILS_ERROR";

// insert message 
export const INSERT_MESSAGES = "INSERT_MESSAGES";
export const INSERT_MESSAGES_LOADING = "INSERT_MESSAGES_LOADING";
export const INSERT_MESSAGES_SUCCESS = "INSERT_MESSAGES_SUCCESS";
export const INSERT_MESSAGES_ERROR = "INSERT_MESSAGES_ERROR";

// read message 
export const READ_MESSAGES = "READ_MESSAGES";
export const READ_MESSAGES_LOADING = "READ_MESSAGES_LOADING";
export const READ_MESSAGES_SUCCESS = "READ_MESSAGES_SUCCESS";
export const READ_MESSAGES_ERROR = "READ_MESSAGES_ERROR";

// ADD THEME LIGHT AND DARK
export const SWITCH_THEME = "SWITCH_THEME";
