//update settings
export const MESSAGES_LIST = "MESSAGES_LIST";
export const MESSAGES_LIST_LOADING = "MESSAGES_LIST_LOADING";
export const MESSAGES_LIST_SUCCESS = "MESSAGES_LIST_SUCCESS";
export const MESSAGES_LIST_ERROR = "MESSAGES_LIST_ERROR";

// ADD THEME LIGHT AND DARK
export const SWITCH_THEME = "SWITCH_THEME";
