const StaticTitle = {
    //Authentication Static Title
    login: "Login",
    loginwithFB:'Login with Facebook',
    loginwithGoogle:'Sign in with Google',
    loginwithEmail:'Login with Email',
    forgotpasserror:'Your email address cannot be found or is not valid. Please try again or create an account',
    or:'or',
    newApp:'New to this app?',
    signup:'Sign Up',
    signin:'Sign In',
    forgotPasswordSignin:'Forgot my password?',
    enterPassword:'Enter Password',
    enterUsaerName:'Enter Email Address',
    backTo:'Back to',
    enterFirstName:'Enter First Name',
    enterLastName:'Enter Last Name',
    confirmPassword:'Confirm Password',
    enterDOB:'Enter Date of Birth',
    termAndConditionText:'By clicking Sign Up, you agree to our,',
    termAndCondition:'Terms and conditions',
    termAndConditionLast:'a confirmation email will be sent to the above email to activate your account.',
    alreadyHaveAccount:'Already have an account?',
    continue:'Continue',
    createProfile:'Create Profile',
    userName:'Username',
    city:'City or Suburb',
    makeModal:'Make and Model of Car',
    colors:'Color of Car',
    imgfiledrequired:'The image field is required.',
    registrationpaper:'The registration paper field is required.',
    vehicalphotorequired:'The vehicle photo field is required.',
    registernumberfieldvalidation:'The registration number may only contain letters and numbers.',
    registernumberfieldrequire:'The registration number field is required.',
    enterUserName:'Enter Username',
    enterCity:'Enter City or Suburb',
    selectCity:'Choose City or Suburb',
    chooseModal:'Make and Model of Car',
    enterColor:'Enter Color of Car',
    selectColor:'Choose Color of Car',
    addDescription:'Add a Description',
    forgotPassword:'Forgot Password',
    resetpassword:'Reset Password',
    confirmationCode:'Enter Confirmation Code',
    enternewpassword:'Enter New Password',
    addRegistrationDetail:'Add registration details',
    linkyouraccount:'Link with your social media accounts',
    rego:'REGO',
    sa:'SA',
    linkwithinsta:'Link with Instagram',
    enterSnapName:'Enter Sanpchat Username',
    enterinstname:'Enter Instagram Username',
    enterfbname:'Enter Facebook Username',
    captureimgfromCamera:'Capture Image from Camera',
    uploadfromgallery:'Upload Image from Gallery',
    filetoupload:'Choose File To Upload',
    registartionDetail:'Registration Details',
    registerContent:'To verify that this vehicle is yours, we require a copy of your registration papers. Only the vehicle registration number, vehicle make, color and registered owner name is required for confirmation and all other information can be omitted if required. Additionally a photo of your vehicle with the number plate visible is required. All information is deleted after confirmation.',
    enterRegisterNumber:'Enter Registration Number',
    attachPaper:'Attach Registration Paper',
    attachPhoto:'Attach Vehicle Photo',
    updateattachPaper:'Update Registration Paper',
    updateattachPhoto:'Update Vehicle Photo',
    saveDetails:'Save Details',
    attchDoc:'Attach Document/Photo',
    linkfb:'Link with Facebook',
    linkinsta:'Link with Instagram',
    linksnap:'Link with Snapchat',
    registerinfoneeded:'You have to fill registration details (REGO)',

    /////// DASHBOARD
    searchbyVehicalNum:'Search Users by Their Vehicle Number',
    searchbyNameNnum:'Search by Name/Number Plate',
    frndList:'Friends List',
    userProfile:'User Profile',
    msges:'Messages',
    changeRegistration:'Change Registration',
    notification:'Notifications',
    whosearchyou:"Who's Searched You..",

    //// PRIVACY SETTINGS 
    privacysettings:'Privacy Settings',
    hideprofile:'Hide Profile',
    hidecity:'Hide City/Suburb',
    hidemodelofcar:'Hide Make/Model and Colour',
    requestforsocial:'Required Request for Socials',
    sharesocial:'Share Social when you Search Someone',
    displayname:'Display Username Instead of Name',
    premiumsetting:'Premium Settings',
    hidesearchuser:'Hide when you Search Users',

    //// FRIEND LIST AND DETAIL 
    noFrnds:"Currently you don't have Friends",
    dummy:'A certain king had a beautiful garden, and in the garden stood a tree which bore golden apples. These apples were always counted, and about the time when they began to grow ripe it was found that every night one of them was gone. The king became very angry at this, and ordered the gardener to keep watch all night under the tree. The gardener set his eldest son to watch; but about twelve o’clock he fell asleep, and in the morning another of the apples was missing. Then the second son was ordered to watch; and at midnight he too fell asleep, and in the morning another apple was gone. Then the third son offered to keep watch; but the gardener at first would not let him, for fear some harm should come to him: however, at last he consented, and the young man laid himself under the tree to watch.',

    //// CHAT
    chatinput:'Type a message',
    moreactions:'More Actions',


    /// PROFILE
    update:'Update',
    updatedetail:'Update Deatils',

    // LOGOUT
    logout:'Are you sure you want to logout?',
    termandcond:'Terms & Conditions',
    subscriptions:'Manage Subscription'
  };
  export { StaticTitle };
  