const StaticTitle = {
    //Authentication Static Title
    login: "Login",
    loginwithFB:'Login with Facebook',
    loginwithGoogle:'Sign in with Google',
    loginwithEmail:'Login with Email',
    or:'or',
    newApp:'New to this app?',
    signup:'Sign Up',
    signin:'Sign In',
    forgotPasswordSignin:'Forgot my password?',
    enterPassword:'Enter Password',
    enterUsaerName:'Enter Email Address',
    backTo:'Back to',
    enterFirstName:'Enter First Name',
    enterLastName:'Enter Last Name',
    confirmPassword:'Confirm Password',
    enterDOB:'Enter Date of Birth',
    termAndConditionText:'By clicking Sign Up, you agree to our,',
    termAndCondition:'Terms and conditions',
    termAndConditionLast:'a confirmation email will be sent to the above email to activate your account.',
    alreadyHaveAccount:'Already have an account?',
    continue:'Continue',
    createProfile:'Create Profile',
    enterUserName:'Enter Username',
    enterCity:'Enter City or Suburb',
    makeModal:'Make and Model of Car',
    enterColor:'Enter Color of Car',
    addDescription:'Add a Description',
    forgotPassword:'Forgot Password',
    resetpassword:'Reset Password',
    confirmationCode:'Enter Confirmation Code',
    enternewpassword:'Enter New Password',
    addRegistrationDetail:'Add registration details',
    linkyouraccount:'Link with your social media accounts',
    rego:'REGO',
    sa:'SA',
    linkwithinsta:'Link with Instagram',
    enterSnapName:'Enter Sanpchat Username',
    captureimgfromCamera:'Capture Image from Camera',
    uploadfromgallery:'Upload Image from Gallery',
    filetoupload:'Choose File To Upload',
    registartionDetail:'Registration Details',
    registerContent:'To verify that this vehicle is yours, we require a copy of your registration papers. Only the vehicle registration number, vehicle make, color and registered owner name is required for confirmation and all other information can be omitted if required. Additionally a photo of your vehicle with the number plate visible is required. All information is deleted after confirmation.',
    enterRegisterNumber:'Enter Registration Number',
    attachPaper:'Attach Registration Paper',
    attachPhoto:'Attach Vehicle Photo',
    saveDetails:'Save Details',
    attchDoc:'Attach Document/Photo'
  };
  export { StaticTitle };
  