// Use DummyData

export const DummyData = [
  {
    Id: 1,
    Owner_Name: "Nydia Daniels",
    Name: "Quilpy",
    Num: "ISD 738",
    Img: "https://i.pravatar.cc/150?img=10",
  },
  {
    Id: 2,
    Owner_Name: "Nydia Daniels",
    Name: "William",
    Num: "ISD 738",
    Img: "https://i.pravatar.cc/150?img=11",
  },
  {
    Id: 3,
    Owner_Name: "Nydia Daniels",
    Name: "Yella",
    Num: "ISD 738",
    Img: "https://i.pravatar.cc/150?img=12",
  },
  {
    Id: 4,
    Owner_Name: "Leah Burton",
    Name: "Storm",
    Num: "ISD 738",
    Img: "https://i.pravatar.cc/150?img=13",
  },
  {
    Id: 5,
    Owner_Name: "Nydia Daniels",
    Name: "Quilpy",
    Num: "ISD 738",
    Img: "https://i.pravatar.cc/150?img=14",
  },
  {
    Id: 6,
    Owner_Name: "Nydia Daniels",
    Name: "William",
    Num: "ISD 738",
    Img: "https://i.pravatar.cc/150?img=14",
  },
  {
    Id: 7,
    Owner_Name: "Nydia Daniels",
    Name: "Yella",
    Num: "ISD 738",
    Img: "https://i.pravatar.cc/150?img=15",
  },
  {
    Id: 8,
    Owner_Name: "Leah Burton",
    Name: "Storm",
    Num: "ISD 738",
    Img: "https://i.pravatar.cc/150?img=16",
  },
  {
    Id: 9,
    Owner_Name: "Nydia Daniels",
    Name: "Quilpy",
    Num: "ISD 738",
    Img: "https://i.pravatar.cc/150?img=17",
  },
  {
    Id: 10,
    Owner_Name: "Nydia Daniels",
    Name: "William",
    Num: "ISD 738",
    Img: "https://i.pravatar.cc/150?img=18",
  },
  {
    Id: 11,
    Owner_Name: "Nydia Daniels",
    Name: "Yella",
    Num: "ISD 738",
    Img: "https://i.pravatar.cc/150?img=20",
  },
  {
    Id: 12,
    Owner_Name: "Leah Burton",
    Name: "Storm",
    Num: "ISD 738",
    Img: "https://i.pravatar.cc/150?img=21",
  },
  {
    Id: 13,
    Owner_Name: "Nydia Daniels",
    Name: "Quilpy",
    Num: "ISD 738",
    Img: "https://i.pravatar.cc/150?img=22",
  },
  {
    Id: 14,
    Owner_Name: "Nydia Daniels",
    Name: "William",
    Num: "ISD 738",
    Img: "https://i.pravatar.cc/150?img=23",
  },
  {
    Id: 15,
    Owner_Name: "Nydia Daniels",
    Name: "Yella",
    Num: "ISD 738",
    Img: "https://i.pravatar.cc/150?img=24",
  },
  {
    Id: 16,
    Owner_Name: "Leah Burton",
    Name: "Storm",
    Num: "ISD 738",
    Img: "https://i.pravatar.cc/150?img=20",
  },
];
