//Login user
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

//User register
export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_LOADING = "USER_REGISTER_LOADING";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";

//Forgot-Reset Password
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_LOADING = "FORGOT_PASSWORD_LOADING";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";

//create profile 1
export const CREATE_PROFILE = "CREATE_PROFILE";
export const CREATE_PROFILE_LOADING = "CREATE_PROFILE_LOADING";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const CREATE_PROFILE_ERROR = "CREATE_PROFILE_ERROR";

//create social profile 1
export const CREATE_SOCIAL_PROFILE = "CREATE_SOCIAL_PROFILE";
export const CREATE_SOCIAL_PROFILE_LOADING = "CREATE_SOCIAL_PROFILE_LOADING";
export const CREATE_SOCIAL_PROFILE_SUCCESS = "CREATE_SOCIAL_PROFILE_SUCCESS";
export const CREATE_SOCIAL_PROFILE_ERROR = "CREATE_SOCIAL_PROFILE_ERROR";

//get car model
export const GET_CAR_MODEL = "GET_CAR_MODEL";
export const GET_CAR_MODEL_LOADING = "GET_CAR_MODEL_LOADING";
export const GET_CAR_MODEL_SUCCESS = "GET_CAR_MODEL_SUCCESS";
export const GET_CAR_MODEL_ERROR = "GET_CAR_MODEL_ERROR";

//get car colour
export const GET_CAR_COLOUR = "GET_CAR_COLOUR";
export const GET_CAR_COLOUR_LOADING = "GET_CAR_COLOUR_LOADING";
export const GET_CAR_COLOUR_SUCCESS = "GET_CAR_COLOUR_SUCCESS";
export const GET_CAR_COLOUR_ERROR = "GET_CAR_COLOUR_ERROR";

// get city
export const GET_CITY = "GET_CITY";
export const GET_CITY_LOADING = "GET_CITY_LOADING";
export const GET_CITY_SUCCESS = "GET_CITY_SUCCESS";
export const GET_CITY_ERROR = "GET_CITY_ERROR";

// fb login
export const SOCIAL_LOGIN = "SOCIAL_LOGIN";
export const SOCIAL_LOGIN_LOADING = "SOCIAL_LOGIN_LOADING";
export const SOCIAL_LOGIN_SUCCESS = "SOCIAL_LOGIN_SUCCESS";
export const SOCIAL_LOGIN_ERROR = "SOCIAL_LOGIN_ERROR";

// register detail
export const REGISTER_DETAIL = "REGISTER_DETAIL";
export const REGISTER_DETAIL_LOADING = "REGISTER_DETAIL_LOADING";
export const REGISTER_DETAIL_SUCCESS = "REGISTER_DETAIL_SUCCESS";
export const REGISTER_DETAIL_ERROR = "REGISTER_DETAIL_ERROR";

// update register detail
export const UPDATE_REGISTER_DETAIL = "UPDATE_REGISTER_DETAIL";
export const UPDATE_REGISTER_DETAIL_LOADING = "UPDATE_REGISTER_DETAIL_LOADING";
export const UPDATE_REGISTER_DETAIL_SUCCESS = "UPDATE_REGISTER_DETAIL_SUCCESS";
export const UPDATE_REGISTER_DETAIL_ERROR = "UPDATE_REGISTER_DETAIL_ERROR";

// ADD THEME LIGHT AND DARK
export const SWITCH_THEME = "SWITCH_THEME";
